name: VLab

secrets:
  vlab_key:
    file: ./.secrets/database.key

networks:
  network:
    driver: bridge

volumes:
  auth-data:
    driver: local

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    attach: false
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PASSWORD_FILE: /run/secrets/vlab_key

  database:
    image: postgres:18.2-alpine3.23
    container_name: database
    restart: always
    attach: false
    secrets:
      - vlab_key
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - auth-data:/var/lib/postgresql  
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: vlab_user
      POSTGRES_PASSWORD_FILE: /run/secrets/vlab_key