name: VLab

secrets:
  vlab_key:
    file: ./.secrets/database.key

networks:
  network:
    driver: bridge

volumes:
  auth-data:
    driver: local

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    attach: false
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker
    secrets:
      - vlab_key
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/up"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api/v1
    container_name: frontend
    restart: always
    attach: false
    ports:
      - 5173:80
    networks:
      - network
    depends_on:
      - backend

  database:
    image: postgres:18.2-alpine3.23
    container_name: database
    restart: always
    attach: false
    secrets:
      - vlab_key
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - auth-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: vlab_user
      POSTGRES_PASSWORD_FILE: /run/secrets/vlab_key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlab_user -d database"]
      interval: 5s
      timeout: 5s
      retries: 10